const CONFIG={apiUrl:'PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE',client:'ИП Сергеева'};
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Math.round(n||0));
const rub=n=>fmt(n)+' ₽';
let DATA=null;
async function load(){setStatus('Загрузка данных…');try{if(CONFIG.apiUrl.startsWith('PASTE_')) throw new Error('API_URL_NOT_SET');const r=await fetch(CONFIG.apiUrl);if(!r.ok)throw new Error('HTTP '+r.status);DATA=await r.json();render();setStatus('Обновлено: '+new Date().toLocaleString('ru-RU'));}catch(e){DATA=demo();render();setStatus(e.message==='API_URL_NOT_SET'?'Демо-режим — вставьте URL Apps Script в app.js':'Не удалось загрузить API, показаны демо-данные');}}
function demo(){return {client:CONFIG.client,days:[{date:'06.08',sales:18400,ads:2200,profit:6100},{date:'07.08',sales:22100,ads:2450,profit:7700},{date:'08.08',sales:19700,ads:2380,profit:6500},{date:'09.08',sales:25100,ads:2600,profit:8900},{date:'10.08',sales:27800,ads:2950,profit:9600},{date:'11.08',sales:28450,ads:3240,profit:8720}],products:[{nmId:311273258,name:'Товар 311273258',orders:8,sales:13800,ads:1120,profit:4200,cpo:140},{nmId:1126341182,name:'Товар 1126341182',orders:5,sales:9100,ads:1260,profit:2780,cpo:252},{nmId:1124948592,name:'Товар 1124948592',orders:4,sales:5550,ads:860,profit:1740,cpo:215}]};}
function render(){document.getElementById('client').textContent=DATA.client||CONFIG.client;const days=DATA.days||[];const total=(k)=>days.reduce((s,d)=>s+(+d[k]||0),0),sales=total('sales'),ads=total('ads'),profit=total('profit'),orders=(DATA.products||[]).reduce((s,p)=>s+(+p.orders||0),0),drr=sales?ads/sales*100:0,cpo=orders?ads/orders:0;const cards=[['Заказы',fmt(orders)],['Продажи',rub(sales)],['Реклама',rub(ads)],['ДРР',drr.toFixed(1)+'%'],['Прибыль',rub(profit)],['CPO',rub(cpo)]];document.getElementById('kpis').innerHTML=cards.map(x=>`<div class='kpi'><div class='label'>${x[0]}</div><div class='value'>${x[1]}</div></div>`).join('');renderChart(days);renderProducts(DATA.products||[]);renderAlerts(DATA.products||[]);}
function renderProducts(ps){document.getElementById('productCount').textContent=ps.length+' SKU';document.getElementById('products').innerHTML=ps.map(p=>`<div class='product'><div class='ph'></div><div><h3>${p.name||('Артикул '+p.nmId)}</h3><div class='metrics'><span>Заказы<b>${fmt(p.orders)}</b></span><span>Продажи<b>${rub(p.sales)}</b></span><span>Реклама<b>${rub(p.ads)}</b></span><span>CPO<b>${rub(p.cpo)}</b></span><span>Прибыль<b>${rub(p.profit)}</b></span><span>Артикул<b>${p.nmId}</b></span></div></div></div>`).join('');}
function renderAlerts(ps){let a=[];ps.forEach(p=>{if(p.cpo>250)a.push(`<div class='alert bad'>Высокий CPO у <b>${p.nmId}</b>: ${rub(p.cpo)}</div>`);if(p.profit<0)a.push(`<div class='alert bad'><b>${p.nmId}</b> работает в минус: ${rub(p.profit)}</div>`)});if(!a.length)a.push(`<div class='alert good'>Критичных отклонений сейчас нет.</div>`);document.getElementById('alerts').innerHTML=a.join('');}
function renderChart(ds){const c=document.getElementById('chart'),ctx=c.getContext('2d'),w=c.width,h=c.height,p=35;ctx.clearRect(0,0,w,h);const max=Math.max(1,...ds.flatMap(d=>[d.sales,d.ads,d.profit]));ctx.strokeStyle='#e5e7eb';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=p+(h-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}[['sales','#111'],['ads','#8c939a'],['profit','#b9bec4']].forEach(([k,col])=>{ctx.strokeStyle=col;ctx.lineWidth=3;ctx.beginPath();ds.forEach((d,i)=>{let x=p+(w-2*p)*(i/Math.max(1,ds.length-1)),y=h-p-(h-2*p)*(d[k]/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});ctx.fillStyle='#737b84';ctx.font='12px Arial';ds.forEach((d,i)=>{let x=p+(w-2*p)*(i/Math.max(1,ds.length-1));ctx.fillText(d.date,x-14,h-10)});}
function setStatus(s){document.getElementById('status').textContent=s}document.getElementById('refresh').onclick=load;document.getElementById('period').onchange=render;load();
